---
speakers:
  - name: John Gunderman
    affiliation: Google
    title: 'SPDY: Making the Web Faster'
    email: 'johngunderman@google.com'
    bio: >
      We'll take a look at the future of HTTP, and how Google's SPDY protocol
      addresses the shortcomings of HTTP 1.1. Come learn about how SPDY is
      behind the scenes, speeding up your web browsing!


      John Gunderman graduated from CWRU in 2013 with a degree in Computer Science.
      He interned twice at Google, working on Google's MySQL deployment. John now
      works full time on one of Google's technical infrastructure teams. In his
      free time, John enjoys juggling, long backpacking trips in the Sierras,
      and fine whiskys.

  - name: Brian Stack
    affiliation: Yelp
    title: Is it Working? Lessons Learned about Monitoring Large Web Applications
    email: 'bstack@yelp.com'
    bio: >
      You've built the site, now how do you know it's working?  Modern websites
      are made up of a myriad of moving parts that all must work in harmony.  How
      can you know that your website is working and how can you figure out what's
      wrong as quickly as possible when your website inevitably breaks?  A robust
      and performant monitoring infrastructure makes a world of difference for your
      infrastructure and developers alike.  Come learn about how Yelp monitors
      its infrastructure and makes sure the website works!


      Brian Stack graduated from CWRU in 2013 with a BS in Computer Science.
      He started an internship at Yelp the summer after his junior year and hasn't
      looked back since.  He came back to the infrastructure team after finishing
      his senior year and has been working to keep the site fast and keeping
      developers productive ever since.  While in school he worked on figuring out
      how networks actually work with Mark Allman (neither of them have quite
      figured it out yet).

  - name: Tom Dooner
    affiliation: Causes
    title: 'Putting Mobile First: Increasing Performance with Progressive Enhancement'
    twitter: '@tomdooner'
    email: 'tomdooner@gmail.com'
    bio: >
      40% of users will abandon websites that take over three seconds to load.
      Even if your web application is straddling this boundary, by adopting a mobile-first
      design paradigm your web application will be more responsive on all browsers
      and devices. This talk will cover some common progressive enhancement techniques
      and how to make sure you're not leaving any users behind.


      Tom Dooner is a Software Engineer at Causes, the world's largest online campaigning
      platform. Born and raised a web developer, he recently moved from Cleveland to
      San Francisco to follow his dream of writing code that empowers its users.
      He has helped engineer Causes's recent relaunch and is looking forward to
      building exciting features in the future. Tom is a recent graduate of CWRU.

  - name: Matt O'Donnell
    affiliation: Leandog
    title: Stateless / Immutable Webapps - Stealing Ideas from Functional Patterns
    bio: >
      How can we utilize functional principles(SOC, data-in-data-out functions, etc...),
      while still keeping standard but very non-functional tools while working within the
      python ecosystem. How can these drastically different paradigms fit together?


      Some great things happened through a years worth of experimentation. Tests are fast,
      small, and easy(less use of mocks and other advanced testing tools) out of the box.
      What data a view or function actually needs is readably apparent, mocking database calls
      become completely unnecessary (due to the makeup of the new data models), other kind of
      data sources were trivial to convert; data just looked like data no matter where it
      came from(the file system, an ORM, redis, mongo).


      What might we discover by looking at a codebase from a different perspective? I would
      like to share some of this journey, talk about separating data from functionality(the
      good times, the bad times), some of the code that emerged, and things we can take
      away from this grand experiment.  


      Matt is a web developer at LeanDog in Cleveland, Ohio. By day, he makes engaging
      and useful things for the web. By night, he hacks on python in search of a
      better understanding around the definition and practice of "craftsmanship".

  - name: Tim Downs
    affiliation: Sociagram
    title: 'Adventures in Service Oriented Architecture: How Sociagram Transcodes and Delivers Video Messages Without Losing Sleep.'
    bio: >
      A look into how Sociagram's architecture provides real time availability
      of their customers' videos while transcoding and optimizing their content.


      Tim is an engineer obsessed with building highly available web applications.
      He joined the team in March of 2013 from Cleveland based Urbancode. Before
      Urbancode he worked to create industry defining social media marketing and
      analytics tools at HubSpot in Cambridge, MA and loyalty platform management
      tools at ePrize in Pleasant Ridge, MI. Tim has a degree in Computer Science
      from Kettering University in Flint, MI. He is an average hockey player, an
      enthusiastic traveller, and devoted bulldog owner.

  - name: Dan Saks
    affiliation: Saks & Associates
    title: Measuring Instead of Speculating
    bio: >
      C is clearly the dominant language for programming embedded
      systems, in large part because it provides convenient and efficient access
      to hardware devices.  C++ offers additional object-oriented facilities
      that provide higher levels of abstraction, yet it remains a distant second
      choice for embedded programming.  Many practicing C programmers assert
      without proof that using C++ objects for hardware accesses is too costly
      to use.  This session explains how to actually measure such claims.  It
      also presents actual measurements showing that some widely-used C
      techniques can actually be much slower than straightforward C++ techniques.


      Dan Saks is the president of Saks & Associates, which offers training
      and consulting in C and C++ and their use in developing embedded systems.
      Dan writes the Programming Pointers column for Embedded.com online.  He
      has written columns for several other publications including The C/C++
      Users Journal, The C++ Report, Embedded Systems Design, and Software
      Development.  With Thomas Plum, he wrote C++ Programming Guidelines, which
      won a Computer Language Magazine Productivity Award as one of the best
      books of 1992.  Dan served as secretary of the ANSI and ISO C++ Standards
      committees and as a member of the ANSI C Standards committee.  More
      recently, he contributed to the CERT Secure C Coding Standard and the CERT
      Secure C++ Coding Standard.  He is also a Microsoft MVP (Most Valuable
      Professional).  Dan has a BS in Mathematics from CWRU and an MSE in
      Computer Science from the University of Pennsylvania.

  - name: Chris Gammell
    affiliation: The Amp Hour
    title: A Day In The Life Of An Open Source Analog Electrical Engineer
    bio: >
      In the past, getting your electronics project started and out the door
      quickly meant you either had a huge team at your disposal or you were
      paying a lot for design tools that would allow you to complete a task
      quickly and effectively. More recently, teams, project schedules and
      budgets seem to shrink on a daily basis, with more expected from the final
      output. What is a designer to do? Much like the tools that have revolutionized
      how software designers create their projects, these tools have begun trickling
      into the lives of hardware designers, both in how they create and share their
      projects. Chris Gammell will share how he has utilized many of these open
      source tools and projects to create an educational course around analog
      sensors and how the output of the course will be open source hardware. 

      Chris Gammell is a full time analog electrical engineer and part time
      talker/blogger/podcaster/vidcaster. A 2006 graduate from CWRU, Chris has
      worked in fields such as RF, DSP, silicon manufacturing, precise test and
      measurement manufacturing and most recently, large scale industrial process
      control. Outside of work, Chris has a podcast called The Amp Hour with Dave
      Jones of the EEVblog. This weekly transpacific show (Dave lives in Sydney
      Australia) covers industry news, open source projects, interviews with a
      wide range of guests and fun banter about electronics. Most recently, Chris
      has started a new endeavor called Contextual Electronics, which is a 10
      week course teaching people how to design and build electronics with a
      practical, hands on approach. All products developed through CE are licensed
      as Open Source Hardware to be shared and modified (or sold!) by anyone in the world.

  - name: Isaac White
    affiliation: Microsoft
    title: Lessons Learned from a Career in Technology
    bio: >
      Good engineers always perform a lessons learned activity after completing
      a project in order to improve performance on future projects.  Yet, engineers
      don’t always apply this technique to their lives and careers as they reach
      various milestones.  How much did good grades matter?  What kept me up past
      midnight?  What did moped congestion in Thailand teach me about building
      smarter cars? Together, we will explore how our education, passions, and
      experiences can be leveraged to make us more effective problem solvers.


      Isaac White graduated with a BS in Computer Engineering from Case Western
      Reserve in 2005 where he was a four year member of the men’s basketball team.
      He began his career working for Lockheed Martin as a software engineer in
      the Washington, DC area.  During that time he served in a number of roles
      including software developer, security and database administrator, and
      technical proposal manager while working on contracts for the IRS and TSA.
      In 2010 he earned a MS in information Systems from Johns Hopkins University.
      In May of 2013 he joined Microsoft’s Productivity, Access, and Identity Experience
      (PAIX) group in Redmond, WA where he serves as a software design engineer.


      Prior to leaving the Washington, DC area Isaac served as the head coach of
      the DC Vipers youth men’s basketball program.  He also founded Out of Bounds,
      a non-profit organization, which focuses on educating high school student
      athletes about college athletic scholarship eligibility.  Isaac is an avid
      basketball player, a photo hobbyist, and is enthusiastic about web design 
      and mobile technology.   His passions include talking to young people about
      life and their careers, and using technology to solve the world’s problems.
       

  - name: Kendall Wouters
    affiliation: VK
    title: Coming Soon
    bio: >
      Coming Soon

  - name: Eric Meyer
    keynote: true
    title: "Doing Fun and Unnatural Things With '@font-face{}' in CSS"
    twitter: '@meyerweb'
    bio: >
      Eric Meyer is an American web design consultant and author. He is best known
      for his advocacy work on behalf of web standards, most notably Cascading Style
      Sheets (CSS). Meyer has written a number of books and articles on CSS and
      given many presentations promoting its use.


      Meyer graduated from Case Western Reserve University in 1992 with a BA in
      History, and minors in artificial intelligence, astronomy, and English.
      In 2001, he joined Netscape as an Internet applications manager and remained
      with the company until 2003.  Meyer is currently a consultant for Complex
      Spiral Consulting as well as a founding member of the Global Multimedia
      Protocols Group.
