---
sponsors_2016:
  - name: 'Certified Security Solutions'
    website: 'https://www.css-security.com/'
    image: 'sponsors_ls_2016/css-logo.png'
sponsors_2015:
  - name: 'GenomOncology'
    website: 'http://www.genomoncology.com/'
    image: 'sponsors_ls_2015/genomoncology-logo.png'
  - name: 'National Instruments'
    website: 'http://ni.com/'
    image: 'sponsors_ls_2015/national_instruments-logo.png'
  - name: 'Netronome'
    website: 'http://netronome.com/'
    image: 'sponsors_ls_2015/netronome-logo.png'
  - name: 'Blackstone LaunchPad'
    website: 'http://cwru.thelaunchpad.org/'
    image: 'sponsors_ls_2015/blackstone_launchpad-logo.png'
  - name: 'CWRU Career Center'
    website: 'https://students.case.edu/careers/'
    image: 'sponsors_ls_2015/cwru_career_center-logo.png'
  - name: 'MIM Software'
    website: 'http://www.mimsoftware.com/'
    image: 'sponsors_ls_2015/mim-logo.png'
  - name: 'Framed'
    website: 'http://framed.io/'
    image: 'sponsors_ls_2015/framed-logo.png'
sponsors_2014:
  # Note that some sponsors re-use 2013 logos
  - name: 'USG'
    website: 'http://usg.case.edu'
    image: 'sponsors_ls_2013/usg-logo.png'
  - name: 'Yelp'
    website: 'http://www.yelp.com'
    image: 'sponsors_ls_2013/yelp-logo.png'
  - name: 'Co-op office'
    website: 'http://engineering.case.edu/coop'
    image: 'sponsors_ls_2014/coop-logo.jpg'
  - name: 'BoxCast'
    website: 'https://www.boxcast.com'
    image: 'sponsors_ls_2014/boxcast.png'
  - name: 'Framed Data'
    website: 'http://framed.io'
    image: 'sponsors_ls_2014/framed-data.png'
  - name: 'CameraLends'
    website: 'https://www.cameralends.com'
    image: 'sponsors_ls_2014/cameralends.jpg'
  - name: 'MIM Software'
    website: 'http://www.mimsoftware.com'
    image: 'sponsors_ls_2014/mim-logo.png'
  - name: 'Mongoose Metrics'
    website: 'https://www.mongoosemetrics.com'
    image: 'sponsors_ls_2014/mongoose-metrics.png'
sponsors_2013:
  - name: 'USG'
    website: 'http://usg.case.edu'
    image: 'sponsors_ls_2013/usg-logo.png'
  - name: 'Yelp'
    website: 'http://www.yelp.com'
    image: 'sponsors_ls_2013/yelp-logo.png'
  - name: 'Causes'
    website: 'http://www.causes.com'
    image: 'sponsors_ls_2013/causes-logo.png'
  - name: 'VK'
    website: 'http://www.vkcareers.com'
    image: 'sponsors_ls_2013/vklogo.png'
  - name: 'Google'
    website: 'http://www.google.com'
    image: 'sponsors_ls_2013/google-logo.png'
  - name: 'Microsoft'
    website: 'http://www.microsoft.com'
    image: 'sponsors_ls_2013/microsoft-logo.png'
  - name: 'LeanDog'
    website: 'http://www.leandog.com'
    image: 'sponsors_ls_2013/leandog.png'
